### ISSUE TITLE
vpython starts when PyCharm is indexing packages

### ISSUE THREAD

**Issue by russkel** [BruceSherwood/vpython-jupyter#37]
A restart to my pycharm caused it to routinely start reindexing the packages and generating skeletons.  I then saw a browser window pops up with the vpython no_notebook interface. The indexing process then stalls as it waits for vpython to end (which it never does).

I believe PyCharm is importing the `vpython` package and this causes it to fire up.

One could say it's a PyCharm bug, but I thought I'd raise it here, and also no other packages cause this kind of issue on my system.

**Comment by mwcraig** [comment]
I think it would be useful to change the behavior so that this doesn't happen. When (if?) I finally getting around to trying to fix vpython in the latest spyder it will be necessary to change the current behavior so that an import alone does not trigger all of the supporting mechanisms in the no_notebook case.

**Comment by mwcraig** [comment]
Closing because this has been fixed for the 7.5.0 release (coming very soon).
