### ISSUE TITLE
Notebook demo does not run with combination IPython 7, ipykernel 4

### ISSUE THREAD

**Issue by mwcraig** [BruceSherwood/vpython-jupyter#73]
With the latest master, the notebook demos do not run with the combination of IPython 7 and ipykernel 4. I *think* the fix is to remove the check for `IPython.__version__ >= '7.0.0'` that is now at https://github.com/BruceSherwood/vpython-jupyter/pull/59/files#diff-0999d0903bd243aeab01d37a27725cc4R250

Someone else should check this too...

**Comment by mwcraig** [comment]
Confirmed today that this still doesn't work in latest master....

**Comment by jcoady** [comment]
Hi Matt 

I confirmed that the fix is to remove the check for IPython.__version__ >= '7.0.0' . I tested it using ipykernel 4.10.0 and IPython 7.0.1 . I also tested it with other combinations such as ipykernel 5.0.0 with IPython 7.0.1 and ipykernel 5.0.0 with IPython 6.5.0 . With the change it works in all these combinations. 

You can go ahead and change the lines in rate_control.py from 

if ((IPython.__version__ >= '7.0.0') or
                    (ipykernel.__version__ >= '5.0.0')): 
to 

if (ipykernel.__version__ >= '5.0.0'): 

John
